// SPDX-FileCopyrightText: 2026 Klaus Reimer <k@ailis.de>
// SPDX-License-Identifier: MIT

#include <kaycxx/test/run_tests.hpp>

#include <fstream>
#include <iostream>
#include <optional>
#include <string>
#include <string_view>
#include <unordered_map>

#include "detail/default_reporter.hpp"

namespace kaycxx::test {

namespace {

/** Command selected by command-line arguments. */
enum class command {
    /** Run all tests. */
    run_all,

    /** List all tests. */
    list_tests,

    /** Run one selected test. */
    run_test,

    /** Write a generated CTest include file. */
    write_ctest
};

/**
 * Quotes a value as a CMake bracket argument.
 *
 * @param value  Value to quote.
 * @returns CMake bracket argument.
 */
std::string cmake_quote(std::string_view value) {
    auto equals = std::string();
    while (value.contains("]" + equals + "]")) {
        equals += "=";
    }
    return "[" + equals + "[" + std::string(value) + "]" + equals + "]";
}

/**
 * Writes registered tests as tab-separated id and description pairs.
 *
 * @param registry  Registry containing the tests to list.
 * @param output    Output stream receiving the test list.
 */
void write_test_list(test_registry const& registry, std::ostream& output) {
    for (auto const& test : registry.list_tests()) {
        output << test.id << '\t' << test.description << '\n';
    }
}

/**
 * Writes a CTest include file with one add_test() call per registered test.
 *
 * @param registry    Registry containing the tests to write.
 * @param file_name   CTest include file to write.
 * @param executable  Test executable path to use in add_test() commands.
 * @returns True when the file was written successfully.
 */
bool write_ctest_file(test_registry const& registry, std::string_view file_name, std::string_view executable) {
    auto output = std::ofstream(std::string(file_name));
    if (!output) {
        return false;
    }

    auto const tests = registry.list_tests();
    auto name_counts = std::unordered_map<std::string, std::size_t>();
    for (auto const& test : tests) {
        name_counts[test.description]++;
    }

    output << "# Generated by kaycxx-test. Do not edit.\n\n";
    for (auto const& test : tests) {
        auto test_name = test.description;
        if (name_counts[test.description] > 1) {
            test_name += " [" + test.id + "]";
        }
        output << "add_test(" << cmake_quote(test_name) << " " << cmake_quote(executable) << " --run-test " << cmake_quote(test.id) << ")\n";
    }
    return true;
}

/**
 * Prints command-line usage.
 *
 * @param output  Output stream receiving the help text.
 */
void print_usage(std::ostream& output) {
    output << "Usage:\n"
           << "  test-binary --list-tests\n"
           << "  test-binary --run-test <id>\n"
           << "  test-binary --write-ctest <file> <executable>\n";
}

} // namespace

int run_tests() {
    return run_tests(std::cout);
}

int run_tests(int argc, char* argv[]) {
    auto ansi_mode = kaycxx::term::ansi_mode::automatic;
    auto selected_command = command::run_all;
    auto run_test_id = std::string_view();
    auto ctest_file_name = std::string_view();
    auto ctest_executable = std::string_view();

    for (auto index = 1; index < argc; index++) {
        auto const argument = std::string_view(argv[index]);
        if (argument == "--help") {
            print_usage(std::cout);
            return 0;
        }
        if (argument == "--list-tests") {
            selected_command = command::list_tests;
            continue;
        }
        if (argument == "--write-ctest") {
            if (index + 2 >= argc) {
                std::cerr << "--write-ctest requires <file> and <executable>\n";
                return 2;
            }
            selected_command = command::write_ctest;
            ctest_file_name = std::string_view(argv[++index]);
            ctest_executable = std::string_view(argv[++index]);
            continue;
        }
        if (argument == "--run-test") {
            if (index + 1 >= argc) {
                std::cerr << "--run-test requires <id>\n";
                return 2;
            }
            selected_command = command::run_test;
            run_test_id = std::string_view(argv[++index]);
            continue;
        }

        std::cerr << "Unknown argument: " << argument << '\n';
        print_usage(std::cerr);
        return 2;
    }

    switch (selected_command) {
        case command::run_all:
            return run_tests(std::cout, ansi_mode);
        case command::list_tests:
            write_test_list(default_registry(), std::cout);
            return 0;
        case command::run_test:
            return run_test(run_test_id, std::cout, ansi_mode);
        case command::write_ctest:
            if (!write_ctest_file(default_registry(), ctest_file_name, ctest_executable)) {
                std::cerr << "Unable to write CTest file: " << ctest_file_name << '\n';
                return 1;
            }
            return 0;
    }
    return 2;
}

int run_tests(std::ostream& output) {
    return run_tests(output, kaycxx::term::ansi_mode::automatic);
}

int run_tests(std::ostream& output, kaycxx::term::ansi_mode ansi_mode) {
    return run_tests(default_registry(), output, ansi_mode);
}

int run_tests(test_registry& registry, std::ostream& output) {
    return run_tests(registry, output, kaycxx::term::ansi_mode::automatic);
}

int run_tests(test_registry& registry, std::ostream& output, kaycxx::term::ansi_mode ansi_mode) {
    auto reporter = detail::default_reporter(output, ansi_mode);
    reporter.before_test_suites(registry.num_test_suites(), registry.num_test_cases());
    auto const passed = registry.run(reporter);
    reporter.after_test_suites();
    return passed ? 0 : 1;
}

int run_test(std::string_view id, std::ostream& output, kaycxx::term::ansi_mode ansi_mode) {
    return run_test(default_registry(), id, output, ansi_mode);
}

int run_test(test_registry& registry, std::string_view id, std::ostream& output, kaycxx::term::ansi_mode ansi_mode) {
    auto found = false;
    for (auto const& test : registry.list_tests()) {
        if (test.id == id) {
            found = true;
            break;
        }
    }
    if (!found) {
        output << "Unknown test id: " << id << '\n';
        return 1;
    }

    auto reporter = detail::default_reporter(output, ansi_mode);
    reporter.before_test_suites(registry.num_test_suites(), 1);
    auto const passed = registry.run_test(id, reporter);
    reporter.after_test_suites();
    return passed ? 0 : 1;
}

} // namespace kaycxx::test
