// SPDX-FileCopyrightText: 2026 Klaus Reimer <k@ailis.de>
// SPDX-License-Identifier: MIT

#include <kaycxx/test/run_tests.hpp>

#include <kaycxx/cli.hpp>

#include <fstream>
#include <iostream>
#include <regex>
#include <string>
#include <string_view>
#include <unordered_map>

#include "detail/default_reporter.hpp"

namespace kaycxx::test {

namespace {

/**
 * Quotes a value as a CMake bracket argument.
 *
 * @param value  Value to quote.
 * @returns CMake bracket argument.
 */
std::string cmake_quote(std::string_view value) {
    auto equals = std::string();
    while (value.contains("]" + equals + "]")) {
        equals += "=";
    }
    return "[" + equals + "[" + std::string(value) + "]" + equals + "]";
}

/**
 * Writes registered tests as tab-separated id and description pairs.
 *
 * @param registry  Registry containing the tests to list.
 * @param filter    Test selection filter.
 * @param output    Output stream receiving the test list.
 */
void write_test_list(test_registry const& registry, test_filter const& filter, std::ostream& output) {
    for (auto const& test : registry.list_tests(filter)) {
        output << test.id << '\t' << test.description << '\n';
    }
}

/**
 * Runs tests selected by a filter with the default reporter.
 *
 * @param registry   Registry containing the tests to run.
 * @param output     Output stream receiving test output.
 * @param ansi_mode  ANSI output mode.
 * @param filter     Test selection filter.
 * @returns Process exit code.
 */
int run_filtered_tests(test_registry& registry, std::ostream& output, kaycxx::term::ansi_mode ansi_mode, test_filter const& filter) {
    auto const num_tests = registry.num_test_cases(filter);
    if (num_tests == 0 && (!filter.paths.empty() || filter.name_pattern)) {
        output << "No tests matched\n";
        return 1;
    }

    auto reporter = detail::default_reporter(output, ansi_mode);
    reporter.before_test_suites(registry.num_test_suites(filter), num_tests);
    auto const passed = registry.run(reporter, filter);
    reporter.after_test_suites();
    return passed ? 0 : 1;
}

/**
 * Writes a CTest include file with one add_test() call per registered test.
 *
 * @param registry    Registry containing the tests to write.
 * @param file_name   CTest include file to write.
 * @param executable  Test executable path to use in add_test() commands.
 * @returns True when the file was written successfully.
 */
bool write_ctest_file(test_registry const& registry, std::string_view file_name, std::string_view executable) {
    auto output = std::ofstream(std::string(file_name));
    if (!output) {
        return false;
    }

    auto const tests = registry.list_tests();
    auto name_counts = std::unordered_map<std::string, std::size_t>();
    for (auto const& test : tests) {
        name_counts[test.description]++;
    }

    output << "# Generated by kaycxx-test. Do not edit.\n\n";
    for (auto const& test : tests) {
        auto test_name = test.description;
        if (name_counts[test.description] > 1) {
            test_name += " [" + test.id + "]";
        }
        output << "add_test(" << cmake_quote(test_name) << " " << cmake_quote(executable) << " --run-test " << cmake_quote(test.id) << ")\n";
    }
    return true;
}

} // namespace

int run_tests() {
    return run_tests(std::cout);
}

int run_tests(int argc, char* argv[]) {
    auto const command_name = argc > 0 ? std::string_view(argv[0]) : std::string_view("test");
    auto app = kaycxx::cli::command(command_name, {
        .description = "Runs registered unit tests."
    });
    auto help = app.flag("help", "Show this help").action();
    auto list_tests = app.flag("list-tests", "List registered tests").action();
    auto selected_test = app.option<std::string>("run-test", "ID", "Run one registered test").action();
    auto ctest_file = app.option<std::string>("write-ctest", "FILE", "Write registered tests to a CTest include file").action();
    auto name_pattern = app.option<std::string>("test-name-pattern", 't', "PATTERN", "Run tests whose full description matches PATTERN");
    auto paths = app.parameters<std::string>("PATH", "Run tests from matching files or directories");

    try {
        auto arguments = app.parse(argc, argv);
        if (arguments.get(help)) {
            return app.print_help();
        }

        arguments.validate();

        auto filter = test_filter();
        filter.paths = arguments.get(paths);
        if (arguments.has(name_pattern)) {
            filter.name_pattern = arguments.get(name_pattern);
        }

        if (arguments.get(list_tests)) {
            write_test_list(default_registry(), filter, std::cout);
            return 0;
        }
        if (arguments.has(selected_test)) {
            return run_test(arguments.get(selected_test), std::cout, kaycxx::term::ansi_mode::automatic);
        }
        if (arguments.has(ctest_file)) {
            auto const& file_name = arguments.get(ctest_file);
            if (!write_ctest_file(default_registry(), file_name, command_name)) {
                std::cerr << "Unable to write CTest file: " << file_name << '\n';
                return 1;
            }
            return 0;
        }

        return run_filtered_tests(default_registry(), std::cout, kaycxx::term::ansi_mode::automatic, filter);
    } catch (kaycxx::cli::parse_error const& error) {
        std::cerr << app.name() << ": " << error.what() << '\n';
        std::cerr << "Try '" << app.name() << " --help' for more information.\n";
        return 2;
    } catch (std::regex_error const& error) {
        std::cerr << app.name() << ": Invalid test name pattern (" << error.what() << ")\n";
        return 2;
    }
}

int run_tests(std::ostream& output) {
    return run_tests(output, kaycxx::term::ansi_mode::automatic);
}

int run_tests(std::ostream& output, kaycxx::term::ansi_mode ansi_mode) {
    return run_tests(default_registry(), output, ansi_mode);
}

int run_tests(test_registry& registry, std::ostream& output) {
    return run_tests(registry, output, kaycxx::term::ansi_mode::automatic);
}

int run_tests(test_registry& registry, std::ostream& output, kaycxx::term::ansi_mode ansi_mode) {
    auto reporter = detail::default_reporter(output, ansi_mode);
    reporter.before_test_suites(registry.num_test_suites(), registry.num_test_cases());
    auto const passed = registry.run(reporter);
    reporter.after_test_suites();
    return passed ? 0 : 1;
}

int run_test(std::string_view id, std::ostream& output, kaycxx::term::ansi_mode ansi_mode) {
    return run_test(default_registry(), id, output, ansi_mode);
}

int run_test(test_registry& registry, std::string_view id, std::ostream& output, kaycxx::term::ansi_mode ansi_mode) {
    auto found = false;
    for (auto const& test : registry.list_tests()) {
        if (test.id == id) {
            found = true;
            break;
        }
    }
    if (!found) {
        output << "Unknown test id: " << id << '\n';
        return 1;
    }

    auto reporter = detail::default_reporter(output, ansi_mode);
    reporter.before_test_suites(registry.num_test_suites(), 1);
    auto const passed = registry.run_test(id, reporter);
    reporter.after_test_suites();
    return passed ? 0 : 1;
}

} // namespace kaycxx::test
